// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3EFOurbJW2RGpc8bM4TQdAvm_JlyqHEQ',
    appId: '1:98763962602:web:d9474fcb518bd95b76bf93',
    messagingSenderId: '98763962602',
    projectId: 'chatcito-e30c1',
    authDomain: 'chatcito-e30c1.firebaseapp.com',
    storageBucket: 'chatcito-e30c1.firebasestorage.app',
    measurementId: 'G-R2FJ87BQWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAStDUs0joTRkSvN0uQNms9nSLrNjo128',
    appId: '1:98763962602:android:972c58667c94a31176bf93',
    messagingSenderId: '98763962602',
    projectId: 'chatcito-e30c1',
    storageBucket: 'chatcito-e30c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7m1WbkjzlkKnS7qaaAci4lMjyk1-eaZw',
    appId: '1:98763962602:ios:ff3d5373654642f876bf93',
    messagingSenderId: '98763962602',
    projectId: 'chatcito-e30c1',
    storageBucket: 'chatcito-e30c1.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebaseBdd1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7m1WbkjzlkKnS7qaaAci4lMjyk1-eaZw',
    appId: '1:98763962602:ios:ff3d5373654642f876bf93',
    messagingSenderId: '98763962602',
    projectId: 'chatcito-e30c1',
    storageBucket: 'chatcito-e30c1.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebaseBdd1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3EFOurbJW2RGpc8bM4TQdAvm_JlyqHEQ',
    appId: '1:98763962602:web:87376b718739269576bf93',
    messagingSenderId: '98763962602',
    projectId: 'chatcito-e30c1',
    authDomain: 'chatcito-e30c1.firebaseapp.com',
    storageBucket: 'chatcito-e30c1.firebasestorage.app',
    measurementId: 'G-C7810XZQ61',
  );
}
